[
  {
    id: 10522450,
    name: "Даниил",
    email: "danmaster09@yandex.ru",
    lang: "ru",
    rights: {
      leads: [Object],
      contacts: [Object],
      companies: [Object],
      tasks: [Object],
      mail_access: true,
      catalog_access: true,
      files_access: true,
      status_rights: [Array],
      catalog_rights: null,
      custom_fields_rights: null,
      oper_day_reports_view_access: false,
      oper_day_user_tracking: false,
      is_admin: true,
      is_free: false,
      is_active: true,
      group_id: null,
      role_id: null,
    },
    _links: { self: [Object] },
  },
  {
    id: 10529278,
    name: "Иван Поспелов",
    email: "ivanpospelov@mail.com",
    lang: "ru",
    rights: {
      leads: [Object],
      contacts: [Object],
      companies: [Object],
      tasks: [Object],
      mail_access: false,
      catalog_access: false,
      files_access: false,
      status_rights: [Array],
      catalog_rights: null,
      custom_fields_rights: null,
      oper_day_reports_view_access: false,
      oper_day_user_tracking: false,
      is_admin: false,
      is_free: false,
      is_active: true,
      group_id: null,
      role_id: null,
    },
    _links: { self: [Object] },
  },
  {
    id: 10529282,
    name: "Сатоши Накамото",
    email: "satoshinak@bitgold.com",
    lang: "ru",
    rights: {
      leads: [Object],
      contacts: [Object],
      companies: [Object],
      tasks: [Object],
      mail_access: false,
      catalog_access: false,
      files_access: false,
      status_rights: [Array],
      catalog_rights: null,
      custom_fields_rights: null,
      oper_day_reports_view_access: false,
      oper_day_user_tracking: false,
      is_admin: false,
      is_free: false,
      is_active: true,
      group_id: null,
      role_id: null,
    },
    _links: { self: [Object] },
  },
  {
    id: 10529286,
    name: "Мария Ивановна",
    email: "smokeweed@mail.com",
    lang: "ru",
    rights: {
      leads: [Object],
      contacts: [Object],
      companies: [Object],
      tasks: [Object],
      mail_access: false,
      catalog_access: false,
      files_access: false,
      status_rights: [Array],
      catalog_rights: null,
      custom_fields_rights: null,
      oper_day_reports_view_access: false,
      oper_day_user_tracking: false,
      is_admin: false,
      is_free: false,
      is_active: true,
      group_id: 517618,
      role_id: null,
    },
    _links: { self: [Object] },
  },
  {
    id: 10529290,
    name: "Майк Тайсон",
    email: "miketyson@mail.com",
    lang: "ru",
    rights: {
      leads: [Object],
      contacts: [Object],
      companies: [Object],
      tasks: [Object],
      mail_access: false,
      catalog_access: false,
      files_access: false,
      status_rights: [Array],
      catalog_rights: null,
      custom_fields_rights: null,
      oper_day_reports_view_access: false,
      oper_day_user_tracking: false,
      is_admin: false,
      is_free: false,
      is_active: true,
      group_id: null,
      role_id: null,
    },
    _links: { self: [Object] },
  },
];
[
  {
    id: 1179465,
    name: "Алексей Иванович",
    first_name: "Алексей",
    last_name: "Иванович",
    responsible_user_id: 10522450,
    group_id: 0,
    created_by: 10522450,
    updated_by: 10522450,
    created_at: 1705121615,
    updated_at: 1705121755,
    closest_task_at: null,
    is_deleted: false,
    is_unsorted: false,
    custom_fields_values: null,
    account_id: 31494866,
    _links: { self: [Object] },
    _embedded: { tags: [], catalog_elements: [], companies: [Array] },
  },
  {
    id: 1179427,
    name: "Михаил Потомов",
    first_name: "Михаил",
    last_name: "Потомов",
    responsible_user_id: 10522450,
    group_id: 0,
    created_by: 10522450,
    updated_by: 10522450,
    created_at: 1705121442,
    updated_at: 1705121803,
    closest_task_at: null,
    is_deleted: false,
    is_unsorted: false,
    custom_fields_values: [[Object], [Object], [Object]],
    account_id: 31494866,
    _links: { self: [Object] },
    _embedded: { tags: [], catalog_elements: [], companies: [Array] },
  },
  {
    id: 1179417,
    name: "Алексей Иванович",
    first_name: "Алексей",
    last_name: "Иванович",
    responsible_user_id: 10522450,
    group_id: 0,
    created_by: 10522450,
    updated_by: 10522450,
    created_at: 1705121367,
    updated_at: 1705122000,
    closest_task_at: null,
    is_deleted: false,
    is_unsorted: false,
    custom_fields_values: [[Object], [Object], [Object]],
    account_id: 31494866,
    _links: { self: [Object] },
    _embedded: { tags: [], catalog_elements: [], companies: [Array] },
  },
  {
    id: 1179443,
    name: "Вагит Алекперов",
    first_name: "Вагит",
    last_name: "Алекперов",
    responsible_user_id: 10522450,
    group_id: 0,
    created_by: 10522450,
    updated_by: 10522450,
    created_at: 1705121514,
    updated_at: 1705213496,
    closest_task_at: null,
    is_deleted: false,
    is_unsorted: false,
    custom_fields_values: [[Object], [Object], [Object]],
    account_id: 31494866,
    _links: { self: [Object] },
    _embedded: { tags: [], catalog_elements: [], companies: [Array] },
  },
];
[
  {
    id: 63269018,
    name: "Неразобранное",
    sort: 10,
    is_editable: false,
    pipeline_id: 7653418,
    color: "#c1c1c1",
    type: 1,
    account_id: 31494866,
    _links: { self: [Object] },
  },
  {
    id: 63269022,
    name: "Первичный контакт",
    sort: 20,
    is_editable: true,
    pipeline_id: 7653418,
    color: "#99ccff",
    type: 0,
    account_id: 31494866,
    _links: { self: [Object] },
  },
  {
    id: 63269026,
    name: "Переговоры",
    sort: 30,
    is_editable: true,
    pipeline_id: 7653418,
    color: "#ffff99",
    type: 0,
    account_id: 31494866,
    _links: { self: [Object] },
  },
  {
    id: 63269030,
    name: "Принимают решение",
    sort: 40,
    is_editable: true,
    pipeline_id: 7653418,
    color: "#ffcc66",
    type: 0,
    account_id: 31494866,
    _links: { self: [Object] },
  },
  {
    id: 63269034,
    name: "Согласование договора",
    sort: 50,
    is_editable: true,
    pipeline_id: 7653418,
    color: "#ffcccc",
    type: 0,
    account_id: 31494866,
    _links: { self: [Object] },
  },
  {
    id: 142,
    name: "Успешно реализовано",
    sort: 10000,
    is_editable: false,
    pipeline_id: 7653418,
    color: "#CCFF66",
    type: 0,
    account_id: 31494866,
    _links: { self: [Object] },
  },
  {
    id: 143,
    name: "Закрыто и не реализовано",
    sort: 11000,
    is_editable: false,
    pipeline_id: 7653418,
    color: "#D5D8DB",
    type: 0,
    account_id: 31494866,
    _links: { self: [Object] },
  },
];
[
  {
    id: 553809,
    name: "Покупка бензина",
    price: 10000,
    responsible_user_id: 10529282,
    group_id: 0,
    status_id: 63269026,
    pipeline_id: 7653418,
    loss_reason_id: null,
    created_by: 10522450,
    updated_by: 10522450,
    created_at: 1705121754,
    updated_at: 1705121782,
    closed_at: null,
    closest_task_at: null,
    is_deleted: false,
    custom_fields_values: null,
    score: null,
    account_id: 31494866,
    labor_cost: null,
    _links: { self: [Object] },
    _embedded: { tags: [], companies: [Array], contacts: [Array] },
  },
  {
    id: 553817,
    name: "Покупка газа",
    price: 15000,
    responsible_user_id: 10529290,
    group_id: 0,
    status_id: 63269030,
    pipeline_id: 7653418,
    loss_reason_id: null,
    created_by: 10522450,
    updated_by: 10522450,
    created_at: 1705121803,
    updated_at: 1705121903,
    closed_at: null,
    closest_task_at: null,
    is_deleted: false,
    custom_fields_values: null,
    score: null,
    account_id: 31494866,
    labor_cost: null,
    _links: { self: [Object] },
    _embedded: { tags: [], companies: [Array], contacts: [Array] },
  },
  {
    id: 553793,
    name: "Покупка нефти",
    price: 120000,
    responsible_user_id: 10529278,
    group_id: 0,
    status_id: 63269022,
    pipeline_id: 7653418,
    loss_reason_id: null,
    created_by: 10522450,
    updated_by: 10522450,
    created_at: 1705121567,
    updated_at: 1705121917,
    closed_at: null,
    closest_task_at: null,
    is_deleted: false,
    custom_fields_values: null,
    score: null,
    account_id: 31494866,
    labor_cost: null,
    _links: { self: [Object] },
    _embedded: { tags: [], companies: [Array], contacts: [Array] },
  },
  {
    id: 553831,
    name: "Списание основных средств",
    price: 1000000,
    responsible_user_id: 10529286,
    group_id: 517618,
    status_id: 63269034,
    pipeline_id: 7653418,
    loss_reason_id: null,
    created_by: 10522450,
    updated_by: 10522450,
    created_at: 1705121946,
    updated_at: 1705121960,
    closed_at: null,
    closest_task_at: null,
    is_deleted: false,
    custom_fields_values: null,
    score: null,
    account_id: 31494866,
    labor_cost: null,
    _links: { self: [Object] },
    _embedded: { tags: [], companies: [Array], contacts: [Array] },
  },
  {
    id: 553833,
    name: "Закупка техники",
    price: 500000,
    responsible_user_id: 10529278,
    group_id: 0,
    status_id: 142,
    pipeline_id: 7653418,
    loss_reason_id: null,
    created_by: 10522450,
    updated_by: 10522450,
    created_at: 1705122000,
    updated_at: 1705122018,
    closed_at: 1705122018,
    closest_task_at: null,
    is_deleted: false,
    custom_fields_values: null,
    score: null,
    account_id: 31494866,
    labor_cost: null,
    _links: { self: [Object] },
    _embedded: { tags: [], companies: [Array], contacts: [Array] },
  },
];
